@startuml
title 給与計算を追加したクラスのUML

class 社員 {
  +起立する ()
  +給料を計算する ()
}
class 担当 {
  +起立する ()
  +給料を計算する ()
}
class 主任 {
  +起立する ()
  +給料を計算する ()
}
class 部長 {
  +起立する ()
  +給料を計算する ()
}

社員 <|-- 担当
社員 <|-- 主任
社員 <|-- 部長
@enduml
